apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: awarder
  name: awarder
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'awarder:latest'
  source:
    git:
      ref: master
      uri: 'https://github.com/akhil-rane/Ludus.git'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: dockerfiles/awarder/Dockerfile
      env:
        - name: ludus_secret
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: ludussecret
      from:
        kind: ImageStreamTag
        name: 'python:3.6'
        namespace: openshift
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: awarder.github.secret
      type: GitHub
    - generic:
        secret: awarder.generic.secret
      type: Generic
    - type: ConfigChange
    - imageChange:
      type: ImageChange
status:
  lastVersion: 0