apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: event-listener
  name: event-listener
  namespace: aiops-kubeflow
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'event-listener:latest'
  source:
    git:
      ref: master
      uri: 'https://github.com/akhil-rane/Ludus.git'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: dockerfiles/event_listener/Dockerfile
      env:
        - name: ludus_secret
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: ludussecret
      from:
        kind: ImageStreamTag
        name: 'python:3.6'
        namespace: openshift
    type: Docker
  successfulBuildsHistoryLimit: 5
status:
  lastVersion: 0